import { CardComparison } from "@/components/CardComparison";
import { Header } from "@/components/Header";
import { SideMenu } from "@/components/SideMenu";
import { useUser } from '@clerk/clerk-react';
import { UserButton } from "@clerk/nextjs";
import Head from "next/head";

export default function Dashboard() {
  const { isLoaded, isSignedIn } = useUser();

  if (!isLoaded || !isSignedIn) {
    return null;
  }

  return (
    <>
      <Head>
        <UserButton afterSignOutUrl="/" />
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen items-center justify-center bg-gradient-to-br from-emerald-600 to-fuchsia-200">
        <Header />
        <SideMenu path="/">Principal</SideMenu>
        <CardComparison />
      </main>
    </>
  );
}
