import { CardPlayer } from "@/components/Card";
import { Header } from "@/components/Header";
import { SideMenu } from "@/components/SideMenu";
import { useUser } from '@clerk/clerk-react';
import { UserButton } from "@clerk/nextjs";
import Head from "next/head";

export default function Dashboard() {
  const { isLoaded, isSignedIn } = useUser();

  if (!isLoaded || !isSignedIn) {
    return null;
  }
  return (
    <>
      <Head>
        <UserButton afterSignOutUrl="/" />
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen items-center justify-center bg-gradient-to-br from-fuchsia-100 to-emerald-600">
        <Header />
        <SideMenu />
        <div className="grid grid-cols-2 gap-4">
          <div className="flex-col items-center justify-center">
            
          </div>
          <div className="p-10">
            <CardPlayer />
          </div>
        </div>

      </main>
    </>
  );
}
