import { CardComparison } from "@/components/CardComparison";
import { Header } from "@/components/Header";
import { SideMenu } from "@/components/SideMenu";
import { Button } from "@/components/ui/button";
import { useUser } from '@clerk/clerk-react';
import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import { useState } from "react";
import { Menu } from 'react-feather';

export default function Dashboard() {
  const { isLoaded, isSignedIn } = useUser();
  const [sideMenuVisible, setSideMenuVisible] = useState(false);

  if (!isLoaded || !isSignedIn) {
    return null;
  }

  return (
    <>
      <Head>
        <UserButton afterSignOutUrl="/" />
        <title>Comparar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="flex flex-col flex-grow">
          <Header />
          <main className="flex-grow bg-gradient-to-br from-emerald-200 to-teal-800">
            {sideMenuVisible && (
              <SideMenu path="/">Principal</SideMenu>
            )}
             <Button className="absolute left-48 top-0 bg-transparent w-16 h-14 hover:bg-transparent" 
              onClick={() => setSideMenuVisible(!sideMenuVisible)} >
              <Menu size={24} /> 
             </Button>
            <CardComparison />
          </main>
        </div>
      </div>
    </>
  );
}
