import { CardPlayerHome } from '@/components/CardHome';
import { Header } from "@/components/Header";
import { SideMenu } from "@/components/SideMenu";
import { Button } from "@/components/ui/button";
import Head from "next/head";
import { useState } from "react";
import { Menu } from 'react-feather';
import { CiCircleList } from "react-icons/ci";
import { MdFlag } from "react-icons/md";
import { SlChemistry } from "react-icons/sl";
import { VscGitCompare } from "react-icons/vsc";

export default function Home() {
  const [sideMenuVisible, setSideMenuVisible] = useState(false);

  return (
    <>
      <Head>
        <title>Futeasports</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="flex flex-col flex-grow">
          <main className="flex-grow items-center justify-center bg-gradient-to-br from-cyan-100 to-cyan-600">
            <Button className="absolute left-48 top-0 bg-transparent w-16 h-14 hover:bg-transparent"
              onClick={() => setSideMenuVisible(!sideMenuVisible)} >
              <Menu size={24} />
            </Button>
            <Header />
            {sideMenuVisible && (
              <div className="absolute left-0 top-47 w-48 z-50 shadow-md bg-teal-950">
                <div className="p-4">
                  <SideMenu
                    path="/get-player"
                    icon={
                      [
                        <CiCircleList className="text-green-50" key="icon1" />,
                        <VscGitCompare className="text-green-50" key="icon2" />,
                        <SlChemistry className="text-green-50" key="icon2" />
                      ]
                    }
                    multiPath={["/", "/get-player", "/squad-builder"]}
                    accLength={2} menuTitle="Jogadores">{["Listagem", "Comparar jogador", "Montador de elencos"]}
                  </SideMenu>
                  <SideMenu icon={[<MdFlag className="text-green-600" key="icon3" />]}
                    path="/flags" menuTitle="Jogos" >{["Bandeiras"]}
                  </SideMenu>
                </div>
              </div>
            )}
            <div>
              <CardPlayerHome />
            </div>
          </main>
        </div>
      </div>
    </>
  );
}