import { Header } from "@/components/Header";
import { SideMenu } from "@/components/SideMenu";
import { Button } from "@/components/ui/button";
import Head from "next/head";
import { useState } from "react";
import { Menu } from 'react-feather';

export default function Home() {
  const [sideMenuVisible, setSideMenuVisible] = useState(true);

  return (
    <>
      <Head>
        <title>Futeasports</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen items-center justify-center bg-gradient-to-br from-cyan-100 to-cyan-600">
        <Button className=" bg-transparent absolute ml-48 w-12h-10" onClick={() => setSideMenuVisible(!sideMenuVisible)}>
          <Menu size={16} />
          {sideMenuVisible ? '' : ''}
        </Button>
        <Header />
        {sideMenuVisible && (
          <SideMenu path="/get-player">Comparar jogador</SideMenu>
        )}
      </main>
    </>
  );
}