import { Header } from "@/components/Header";
import { Menu } from "@/components/Menu";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Futeasports</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen items-center justify-center bg-green-300">
      <Header />
      <Menu path="/get-player">Get Player</Menu>

      </main>
    </>
  );
}